Add types for jobs
PostHog/plugin-scaffold pull request #16
Opened 2021-04-30 09:25 UTC by mariusandra

This is a WIP that adds types to an experimental syntax for jobs as described here: https://github.com/PostHog/plugin-server/pull/325

The following will work after this is merged:

```ts
import { CreatePluginMeta, MetaJobsInput } from '@posthog/plugin-scaffold'

type Meta = CreatePluginMeta<{
    config: {
        localhostIP: string
    }
    attachments: {
        maxmindMmdb?: PluginAttachment
    }
    global: {
        ipLookup?: Reader<Response>
    }
    jobs: {
        flushBatch: (ops: { batch: string[]; retryCount?: number }) => Promise<void>
    }
}>

export const jobs: MetaJobsInput<Meta> = {
    flushBatch: async ({ batch, retryCount = 0 }, { jobs }) => {
        const resp = await fetch('https://httpbin.org/post', {
            method: 'post',
            body: JSON.stringify(batch),
            headers: { 'Content-Type': 'application/json' },
        })
        if (resp.status !== 200) {
            if (retryCount > 5) {
                console.error('Could not post batch', batch)
                return
            }
            jobs.runIn(30, 'seconds').flushBatch({ batch, retryCount: retryCount + 1 })
        }
    },
}

export async function setupPlugin({ jobs }: Meta) {
    await jobs.runNow().flushBatch({ batch: [] })
}
```

The `meta.jobs` is fully typed. The `jobs` export unfortunately has to go through `MetaJobsInput<Meta>` when declaring (or it could be `Meta['__jobsInput']` perhaps?), as the output of `meta.jobs` has a different structure than the input. `meta.jobs` runs all the jobs via a wrapper like `jobs.runIn(30, 'minutes').flushBatch()`....

Obviously this should be merged only once we agree on the structure...

2021-04-30 10:18 UTC, yakkomajuri reviewed
I'm not particularly opinionated, but my one comment would be that I would intuitively expect to pass a function as a parameter to another to run a task/job. That's the case with `setTimeout`, `setInterval`, `node-schedule`, etc.

Where instead of:

```
jobs.runNow().flushBatch({ batch: [] })
```

We'd have:

```
jobs.runNow(() => flushBatch({ batch: [] }))

// or

jobs.runNow(someJobFunc)
```

This discussion is completely external to the implementation, so just speaking about what would feel "natural" to me. I do understand we have a tradeoff between feel and the implementation behind the scenes. 

And like I said, not very opinionated.

2021-04-30 10:18 UTC, yakkomajuri commented on src/types.ts
> +    jobs?: Record<string, (opts?: any) => any>
maybe?
```
Record<string, JobFunction>
```

2021-04-30 10:18 UTC, yakkomajuri commented on src/types.ts
> +type CreatePluginMetaBase<Input extends MetaInput> = PluginMeta & {
one step closer to https://www.metabase.com/

2021-04-30 10:59 UTC, mariusandra commented on src/types.ts
> +    jobs?: Record<string, (opts?: any) => any>
👍

2021-04-30 10:59 UTC, mariusandra commented on src/types.ts
> +type CreatePluginMetaBase<Input extends MetaInput> = PluginMeta & {
not an accident! :D

2021-04-30 11:01 UTC, mariusandra commented
It might feel natural, but like you said yourself, the implementation gets in the way. We have no idea when this function will be run... nor on which server. The only thing we know is that we need to store `jobName` and `payload` in the database somehow. 

Within those constraints I'm open to any kind of suggestion or simplification of the API!

2021-04-30 17:43 UTC, Twixes commented
What file is the implementation of this in (in PostHog/plugin-server#325)?

2021-04-30 17:48 UTC, Twixes commented
Ah, so it's https://github.com/PostHog/plugin-server/pull/351

2021-05-04 13:57 UTC, Twixes approved these changes
Looks like this needs reworking because of jobs API changes https://github.com/PostHog/plugin-server/pull/351#issuecomment-831252578

2021-05-04 13:59 UTC, Twixes requested changes
Sorry, wrong review, I wanted this to be 🔴  🟥 🙅  RED

2021-05-06 09:10 UTC, mariusandra commented
Let's try again!

2021-05-06 09:14 UTC, mariusandra commented
Here's a plugin using this code: https://github.com/PostHog/session-tracker-plugin/pull/2/files

2021-05-07 11:20 UTC, Twixes reviewed
Made two suggestions, implemented them in https://github.com/PostHog/plugin-scaffold/pull/17

2021-05-07 11:20 UTC, Twixes commented on src/types.ts
> +export type MetaJobsInput<M extends PluginMeta> = {
I think this could be called `PluginJobs`, which would be more similar to other such types and more obvious?

2021-05-07 11:20 UTC, Twixes commented on src/types.ts
> +export type CreatePluginMeta<Input extends MetaInput> = PluginMeta & {
This is named like a function (starting with a verb) on top of plain `PluginMeta`, but if this is the way we'd like devs to use for typing, we should only expose this really. Could we rename this to `PluginMeta` and rename the "dumb" base interface to `BasePluginMeta`?

2021-05-07 11:23 UTC, mariusandra commented on src/types.ts
> +export type MetaJobsInput<M extends PluginMeta> = {
Good for me

2021-05-07 11:23 UTC, mariusandra commented on src/types.ts
> +export type CreatePluginMeta<Input extends MetaInput> = PluginMeta & {
Great!

2021-05-07 11:23 UTC, merged